apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_PASSWORD: bXlwYXNzd29yZA==

#in the first submission I just used the command kubectl create secret generic db-secret --from-literal=DB_PASSWORD=....
#but here is the yaml version